apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-secret-watcher
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","delete","watch"]